### ISSUE TITLE
socket.gaierror: [Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by wanghonglei5181** [gamegos/cesi#16]
Hi
My cesi server can’t start,I don’t know why.
When I run python web.py,there is an error occurred.
Help me!!!
###### 
- Running on http://<127.0.0.1>:5000/
  Traceback (most recent call last):
  File "web.py", line 535, in <module>
    app.run(debug=True, use_reloader=True, host=HOST)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 739, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.6/site-packages/werkzeug/serving.py", line 613, in run_simple
    test_socket.bind((hostname, port))
  File "<string>", line 1, in bind
  socket.gaierror: [Errno -5] No address associated with hostname
  #################################
  Here is my cesi.conf

[node:<node_name>]
;username = <username>
;password = <password>
host = <10.13.2.49>
port = <9001>

[node:<node_name2>]
;username = <username>
;password = <password>
;host = <hostname>
;port = <port>

;[environment:<environment_name>]
;members = <node_name>, <node_name2>

[cesi]
database = </root/cesi/cesi/userinfo.db>
activity_log = </root/cesi/cesi/access.log>
host = <127.0.0.1>

**Comment by gudubeth** [comment]
There are problems on your configuration. Removing those '<' and '>'s from your config should resolve current problem. See [maintainer's blog post](http://www.gulsahkose.com/2014/09/cesi-centralized-supervisor-interface.html) for additional docs.
