### ISSUE TITLE
A readlog bug

### ISSUE THREAD

**Issue by FAKERINHEART** [gamegos/cesi#20]
I name a subprocess of one supervisor node such as aaa_server.bin. And when I click its 'read log' button, no response, but when I change its name to aaa_server(without '.bin'), I can its button has response.
**I find that the subprocess name can not contain ".", otherwise its readlog function can not be accessed.**
![qq 20160805112137](https://cloud.githubusercontent.com/assets/13352188/17425352/e2b2abfa-5afe-11e6-896e-5eeeb2d1cdfd.jpg)

**Comment by ultimate010** [comment]
I've also have this problem. I fix it in /cesi/static/custom.js. 
```
var classname = "log"; 
var $dia = $("."+classname); 
```
The processname was used as classname, which will cause jquery error, so I change it to "log";
