### ISSUE TITLE
a question how to change cesi the default port not use 5000?

### ISSUE THREAD

**Issue by zqc0512** [gamegos/cesi#41]
a question how to change the default port not use 5000?
in my env not can't use port 5000,how to change the port to other as 8080 80 .
i don't find where to change it . 
how can change it ,thanks so much.

**Comment by zqc0512** [comment]
You can chance node ports in /etc/cesi.conf and You can also change the

can give the example about this?
@alphekimoglu

**Comment by zqc0512** [comment]
You can try to add port to app.run:

    #562 cesi/web.py
    app.run(debug=args.debug, use_reloader=args.use_reloader, host=get_host(), port=8080)

this is ok. i close it.

**Comment by alphekimoglu** [comment]
You can check here for examples
http://ae.koroglu.org/centralized-supervisor-interface-cesi/
