### ISSUE TITLE
sqlite3 ~/cesi/userinfo.sql < userinfo.sql

### ISSUE THREAD

**Issue by thanghl** [gamegos/cesi#48]
sqlite3 ~/cesi/userinfo.sql < userinfo.sql
Error: near line 1: file is encrypted or is not a database
Error: near line 2: file is encrypted or is not a database
Error: near line 3: file is encrypted or is not a database

i can not do ip what i wrong ???
Thanks for help

**Comment by hxpro** [comment]
sqlite3 ~/cesi/userinfo.**db** < userinfo.sql
