### ISSUE TITLE
It could be runing in Python 3?

### ISSUE THREAD

**Issue by zhaoxuan** [gamegos/cesi#50]

**Comment by pleycpl** [comment]
We are working on it. The second version of CESI will work on python3.
https://github.com/gamegos/cesi/tree/v2_api

**Comment by pleycpl** [comment]
We rewrote all the backend codes. And we will rewrite all frontend codes with Reactjs. 
When the frontend is finished, we will merge it.
https://github.com/pleycpl/cesi/tree/v2_api_dev
