### ISSUE TITLE
Interface is puzzled

### ISSUE THREAD

**Issue by 2156yy** [gamegos/cesi#55]
![](https://user-images.githubusercontent.com/24225656/36939524-ce7ff9c6-1f29-11e8-9cad-2a52ff92c743.png)

This web interface is not like the one above. My interface is like the one below. Is this normal? Or is it because I installed something wrong? I installed version CeSI 2.4

![image](https://user-images.githubusercontent.com/23057508/48120276-aed13a80-e2ac-11e8-8f5b-15363f5007dc.png)

**Comment by isbaran** [comment]
Perfectly normal, because of the back end changes interface had to be rewritten. Its under development, should be prettier soon.

**Comment by 2156yy** [comment]
> 完全正常，因为后端更改界面必须重写。它正在开发中，应该很快就会更漂亮。

Is there any time plan for this interface update? And I prefer the first version of the first one，What is this version?

**Comment by 2156yy** [comment]
> Perfectly normal, because of the back end changes interface had to be rewritten. Its under development, should be prettier soon.

> Is there any time plan for this interface update? And I prefer the first version of the first one，What is this version?

**Comment by 2156yy** [comment]
> Perfectly normal, because of the back end changes interface had to be rewritten. Its under development, should be prettier soon.

Is there any time plan for this interface update? And I prefer the first version of the first one，What is this version?

**Comment by hakuno** [comment]
> And I prefer the first version of the first one

I think so. It was fine with Bootstrap's default.
