### ISSUE TITLE
Can't login with default info after building

### ISSUE THREAD

**Issue by kootenpv** [gamegos/cesi#84]
![cesinologin](https://user-images.githubusercontent.com/2746227/94992275-3acb6a00-0589-11eb-9cc8-9aa2227e4341.png)

**Comment by brandonhon** [comment]
I'm guessing you used admin, admin. Here is a pull request that I added with a dockerfile and how to run. You could try that.
https://github.com/gamegos/cesi/pull/80/commits/3fb1d792f879b41f9f276abc832b6d338417992a

**Comment by kootenpv** [comment]
I actually tried that too, but same issue as when installing it myself!

**Comment by brandonhon** [comment]
Are you trying to set the default login in cesi.conf.toml or just using default (user: admin, pass: admin)?

**Comment by kootenpv** [comment]
Yea indeed, I copied the default one and then tried to login with admin/admin

**Comment by brandonhon** [comment]
not sure man. i just built the docker container again and it work fine for me in chrome and firefox. i'm not sure what security settings you have on in your browser but you may try it in a private window.

**Comment by kootenpv** [comment]
I finally got around it again. I have no idea why it does not work on my machine, but can confirm it worked on a different server. So odd.

I'll close as I simply have no reason what could be wrong.
